version: "3.8"
services:
  topology_server:
    build: .
    command: python topology_server.py
    container_name: topology_server
    ports:
      - "6000:6000"
    networks:
      - dmmnet

  server:
    build: .
    command: python main_server.py
    container_name: dmm_server
    depends_on:
      - topology_server
    networks:
      - dmmnet

  client:
    build: .
    # override at runtime with docker-compose scale or replicas
    command: python main_client.py
    environment:
      - TOPOLOGY_URL=http://topology_server:6000
      - CLIENT_PORT=5010
      - ANNOUNCE_ADDRESS=client_1:5010
      - MODEL_NAME=distilgpt2
    ports:
      - "5010" # For single client; when scaling, docker-compose allocates internal names
    networks:
      - dmmnet

networks:
  dmmnet:
    driver: bridge
